# Generated by Django 3.1.3 on 2021-01-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idestado', models.IntegerField()),
                ('idmunicipio', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
    ]
