# Generated by Django 3.1.3 on 2021-01-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0005_auto_20210105_2324'),
        ('municipios', '0002_auto_20210106_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='idestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='estados.estado'),
        ),
    ]
