# Generated by Django 3.1.3 on 2021-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
                ('idestado', models.IntegerField()),
            ],
        ),
    ]
