# Generated by Django 3.1.3 on 2021-01-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0002_auto_20210105_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='id',
            new_name='ids',
        ),
    ]
