# Generated by Django 3.1.3 on 2021-01-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0003_auto_20210105_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='ids',
            new_name='id',
        ),
    ]
